service: gpt-bot

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: "5647100209:AAGmsQh4KSfZaK6sj3G9pp5GMGEpoglOqeM"



functions:
  post:
    handler: handler.hello
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true